### ISSUE TITLE
Question about data loading

### ISSUE THREAD

**Issue by shadowkiller33** [PlusLabNLP/AESOP#2]
Hi! Appreciate your amazing work. I happened to meet the following mistake during data loading, could you tell the version you used?

ImportError: cannot import name 'add_newline_to_end_of_each_sentence' from 'sentence_splitter'

**Comment by sunjiao123sun** [comment]
Hi @shadowkiller33 , could you please add the tracing information for your error?

**Comment by NIL-zhuang** [comment]
> Hi @shadowkiller33 , could you please add the tracing information for your error?

I also encontered this issue, my trace info is listed below
with sentence-splitter version 1.4
```txt
Traceback (most recent call last):
  File "run_eval.py", line 29, in <module>
    from utils import calculate_bleu, calculate_rouge, chunks, parse_numeric_n_bool_cl_kwargs, use_task_specific_params
  File "/data1/AESOP/utils.py", line 34, in <module>
    from sentence_splitter import add_newline_to_end_of_each_sentence
ImportError: cannot import name 'add_newline_to_end_of_each_sentence' from 'sentence_splitter' (/data1/conda/envs/py38/lib/python3.8/site-packages/sentence_splitter/__init__.py)
```

**Comment by sunjiao123sun** [comment]
hi @NIL-zhuang , did you try `pip install sentence_splitter`? If it is not working, please try to install the transformers version as `4.2.0`. 

Hope this is helpful! Please let me know how it goes

**Comment by NIL-zhuang** [comment]
> hi @NIL-zhuang , did you try `pip install sentence_splitter`? If it is not working, please try to install the transformers version as `4.2.0`.
> 
> Hope this is helpful! Please let me know how it goes

Thx, it works fine to me. Also I solved it by applying `"\n".join(nltk.sent_tokenize(x))` to match publiched RougeL score for BART, which serves me well too.

**Comment by sunjiao123sun** [comment]
sounds great! @shadowkiller33 please take a look, and I will close this issue for now. 

feel free to open a new issue when there are new things coming out! good luck with your explorations.
