### ISSUE TITLE
A question about Proprocessing

### ISSUE THREAD

**Issue by StevenTang1998** [PlusLabNLP/AESOP#3]
Hi, when I using the script to proprocessing:
```
python data-processing.py --input_dir raw-data/QQPPos --output_dir processed-data/QQPPos-hf-refine --use_template Y
```
the issue occured:
```
Traceback (most recent call last):
  File "data-processing.py", line 81, in <module>
    src_pure_parses, src_parses = spe.run(src)
  File "/home/tangtianyi/AESOP/helper/utils.py", line 157, in run
    extract_parses(parsed_file)], [e['parse'] for e in extract_parses(parsed_file)]
  File "/home/tangtianyi/AESOP/helper/utils.py", line 82, in extract_parses
    elif new_sent:
UnboundLocalError: local variable 'new_sent' referenced before assignment
```

Or could you provide the processed `processed-data/QQPPos-hf-refine`?
Or it is the same as `processed-data/QQPPos-parse-hf-refine`?

Could you offer some help and wish you a happy day!

**Comment by sunjiao123sun** [comment]
Hi Tianyi, it is the same! sorry i think there were some naming issues when i cleaned the code. let me know if you have further questions!

**Comment by StevenTang1998** [comment]
It can work now! Thank you for your kind help!!
And could you please tell me how long this QQP model has been trained from scratch?

**Comment by StevenTang1998** [comment]
It can work now! Thank you for your kind help!!
