### ISSUE TITLE
UnboundLocalError: local variable 'new_sent' referenced before assignment

### ISSUE THREAD

**Issue by han032206** [PlusLabNLP/AESOP#4]
Hi! I've been trying with the script demo.py, and get the following error when getting the parsing result. It happens in extract_parses function in helper/utils.py, and I'm not sure what the correct logic is here. Could you help with this issue? Thanks!

`Traceback (most recent call last):
  File "demo.py", line 11, in <module>
    src_pure_parses, src_parses = spe.run(file_path)
  File "/data/wangli/project_library/AESOP/helper/utils.py", line 162, in run
    extract_parses(parsed_file)], [e['parse'] for e in extract_parses(parsed_file)]
  File "/data/wangli/project_library/AESOP/helper/utils.py", line 86, in extract_parses
    elif new_sent:
UnboundLocalError: local variable 'new_sent' referenced before assignment
`

**Comment by sunjiao123sun** [comment]
hi @han032206 , this is mostly likely because the corenlp did not successfully execute in your environment, can you double check if your corenlp is working fine? and feel free to set checkpoint to check if you are actually reading corenlp output in.

**Comment by sunjiao123sun** [comment]
please follow up if it is still unsolved @han032206

**Comment by han032206** [comment]
> please follow up if it is still unsolved @han032206

Hi, I double-checked the functionality of corenlp, and it can generate the parsed output file 'demo-input-data.txt.out' properly. I think it's the problem with variables declaration and initialization, probably within these four variables: _new_sent, new_pos, new_parse, new_deps_ in helper/utils.py. Looking forward to your follow-up, Thanks!

**Comment by sunjiao123sun** [comment]
@han032206 can you copy/paste a screenshot of your corenlp output here?

**Comment by han032206** [comment]
**The output of corenlp is as below:**
CompletedProcess(args=['java', '-cp', './evaluation/apps/stanford-corenlp-full-2018-10-05/*', '-Xmx40g', 'edu.stanford.nlp.pipeline.StanfordCoreNLP', '-parse.model', 'edu/stanford/nlp/models/srparser/englishSR.ser.gz', '-annotators', 'tokenize,ssplit,pos,parse', '-ssplit.eolonly', '-outputFormat', 'text', '-outputDirectory', './demo_output/', '-file', 'demo-input-data.txt'], returncode=0, stdout=b'', stderr=b'[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator tokenize\n[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ssplit\n[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator pos\n[main] INFO edu.stanford.nlp.tagger.maxent.MaxentTagger - Loading POS tagger from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [0.7 sec].\n[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator parse\n[main] INFO edu.stanford.nlp.parser.common.ParserGrammar - Loading parser from serialized file edu/stanford/nlp/models/srparser/englishSR.ser.gz ... done [10.2 sec].\n\nProcessing file /data/wangli/project_library/AESOP/demo-input-data.txt ... writing to /data/wangli/project_library/AESOP/demo_output/demo-input-data.txt.out\nAnnotating file /data/wangli/project_library/AESOP/demo-input-data.txt ... done [0.4 sec].\n\nAnnotation pipeline timing information:\nTokenizerAnnotator: 0.1 sec.\nWordsToSentencesAnnotator: 0.0 sec.\nPOSTaggerAnnotator: 0.0 sec.\nParserAnnotator: 0.3 sec.\nTOTAL: 0.4 sec. for 97 tokens at 246.8 tokens/sec.\nPipeline setup: 10.9 sec.\nTotal time for StanfordCoreNLP pipeline: 11.4 sec.\n')

**And the demo-input-data.txt.out file is as below:**
Document: ID=demo-input-data.txt (7 sentences, 97 tokens)

Sentence #1 (11 tokens):
Sentence #Your drawing is so bright even sunshine adjusts focus!

Tokens:
[Text=Sentence CharacterOffsetBegin=0 CharacterOffsetEnd=8 PartOfSpeech=NN]
[Text=#Your CharacterOffsetBegin=9 CharacterOffsetEnd=14 PartOfSpeech=NN]
[Text=drawing CharacterOffsetBegin=15 CharacterOffsetEnd=22 PartOfSpeech=NN]
[Text=is CharacterOffsetBegin=23 CharacterOffsetEnd=25 PartOfSpeech=VBZ]
[Text=so CharacterOffsetBegin=26 CharacterOffsetEnd=28 PartOfSpeech=RB]
[Text=bright CharacterOffsetBegin=29 CharacterOffsetEnd=35 PartOfSpeech=JJ]
[Text=even CharacterOffsetBegin=36 CharacterOffsetEnd=40 PartOfSpeech=RB]
[Text=sunshine CharacterOffsetBegin=41 CharacterOffsetEnd=49 PartOfSpeech=NN]
[Text=adjusts CharacterOffsetBegin=50 CharacterOffsetEnd=57 PartOfSpeech=VBZ]
[Text=focus CharacterOffsetBegin=58 CharacterOffsetEnd=63 PartOfSpeech=NN]
[Text=! CharacterOffsetBegin=63 CharacterOffsetEnd=64 PartOfSpeech=.]

Constituency parse: 
(ROOT
  (S
    (NP (NN Sentence) (NN #Your) (NN drawing))
    (VBZ is)
    (NP
      (ADJP (RB so) (JJ bright))
      (RB even) (NN sunshine))
    (VP (VBZ adjusts)
      (NP (NN focus)))
    (. !)))


Dependency Parse (enhanced plus plus dependencies):
root(ROOT-0, adjusts-9)
compound(drawing-3, Sentence-1)
compound(drawing-3, #Your-2)
nsubj(adjusts-9, drawing-3)
dep(adjusts-9, is-4)
advmod(bright-6, so-5)
amod(sunshine-8, bright-6)
advmod(sunshine-8, even-7)
nsubj(adjusts-9, sunshine-8)
dobj(adjusts-9, focus-10)
punct(adjusts-9, !-11)

**Comment by han032206** [comment]
> @han032206 can you copy/paste a screenshot of your corenlp output here?

I tried to debug and kind of got the logic of how to read the demo-input-data.txt.out file. However, I'm still not getting the right result yet. I think the bugs are within this part of the script, which starts with line 58 in helper/utils.py:

`
def extract_parses(fname):
    f = codecs.getreader('utf-8')(open(fname, 'rb'))

    count = 0
    sentences = []
    data = {'tokens':[], 'pos':[], 'parse':'', 'deps':[]}
    for idx, line in enumerate(f):
        # print(line)
        if line.startswith('Sentence #'):
            new_sent = True
            new_pos = False
            new_parse = False
            new_deps = False
            if idx == 0:
                continue

            # label_sentence(data)
            # print ' '.join(data['tokens'])
            # data['label'] = dataset[count]['label']
            sentences.append(data)
            count += 1

            data = {'tokens':[], 'pos':[], 'parse':'', 'deps':[]}

        # read original sentence
        elif new_sent:
            # data['sent'] = line.strip()
            new_sent = False
            new_pos = True

        # read POS tags
        elif new_pos and line.startswith('[Text='):
            line = line.strip().split()
            w = line[0].split('[Text=')[-1]
            pos = line[-1].split('PartOfSpeech=')[-1][:-1]
            data['tokens'].append(w)
            data['pos'].append(pos)

        # start reading const parses
        elif (new_pos or new_parse) and line.strip() != '':
            new_pos = False
            new_parse = True
            data['parse'] += ' '+line.strip()
            data['pure_parse'] = convert_str(data['parse'])

        # start reading deps
        elif line.strip() == '':
            new_parse = False
            new_deps = True

        elif new_deps and line.strip() != '':
            line = line.strip()[:-1].split('(',1)
            rel = line[0]
            x1, x2 = line[1].split(', ')
            x1 = x1.replace("'", "")
            x2 = x2.replace("'", "")
            x1 = int(x1.rsplit('-', 1)[-1])
            x2 = int(x2.rsplit('-', 1)[-1])
            data['deps'].append((rel, x1 - 1, x2 - 1))

        else:
            new_deps = False

    # add last sentence
    # label_sentence(data)
    # data['label'] = dataset[count]['label']
    sentences.append(data)

    f.close()

    return sentences`

**Comment by sunjiao123sun** [comment]
@han032206 , let's do some debugging here. can you set a checkpoints to see if the program can ever enter the if clause? that should be where the variable is declared.

**Comment by han032206** [comment]
> @han032206 , let's do some debugging here. can you set a checkpoints to see if the program can ever enter the if clause? that should be where the variable is declared.

Thanks for the follow-up, since the first line of demo-input-data.txt.out file does not start with 'Sentence #', I tried to do the declaration outside the for loop and declare all the four variables to be False. However, there still remains bugs and the result is not right. I think maybe there are some naming issues here.

**Comment by sunjiao123sun** [comment]
what's the version of the stanford corenlp you are using? changing the declaration will not work

**Comment by han032206** [comment]
> what's the version of the stanford corenlp you are using? changing the declaration will not work

I just downloaded the requirements as provided in this link https://drive.google.com/file/d/1MP9k48BuBCdAPhWXjfuq7Cl9b9ZIdAPB/view?usp=sharing. 
I think it's stanford-corenlp-3.9.2.

**Comment by sunjiao123sun** [comment]
emm, let's try using stanford-corenlp-full-2016-10-31 @han032206

**Comment by han032206** [comment]
> emm, let's try using stanford-corenlp-full-2016-10-31 @han032206

Is the Shift-Reduce Constituency Parser 'edu/stanford/nlp/models/srparser/englishSR.ser.gz' available in stanford-corenlp-full-2016-10-31? I got the error 
java.io.IOException: Unable to open "edu/stanford/nlp/models/srparser/englishSR.ser.gz" as class path, filename or URL
when using stanford-corenlp-full-2016-10-31.

**Comment by han032206** [comment]
> emm, let's try using stanford-corenlp-full-2016-10-31 @han032206

Thanks for the help and it can work now! I will share the other bugs I encountered when running the demo.py for your reference.
1. There has been one bug fixed in helper/utils.py, line 76. I put 'if data != {'tokens':[], 'pos':[], 'parse':'', 'deps':[]}' here, and it can work properly.
2. Miss the requirement of 'sacrebleu' and 'git' in 'requirement.txt'
3. Torch version should be 1.8.0, however in requirement.txt, there are two versions of torch provided.
4. I thought that 'sentence_splitter' is a python package, but it turned out to be a py file, and it was still missed in the repo.
