### ISSUE TITLE
Some question about processed data of AESOP

### ISSUE THREAD

**Issue by Jessicajr** [PlusLabNLP/AESOP#5]
Hi，I am currently following your work AESOP, and there seems to be something wrong with the processed data provided through google link on the github rep.  
The diverse folder of QQPPos contains preprocessed file of Paranmt(as follow) while the actual preprocessed data of QQPPos seems to be absent in the zip file.  It will be really kind of you if you could provide a link of QQPPos processed data .

![image](https://user-images.githubusercontent.com/47965858/172537275-79218e1c-6278-4c32-b0eb-4dec0ee81ed8.png)

**Comment by sunjiao123sun** [comment]
hi @Jessicajr , you can generate those preprocessed files by running the script (which is in readme.md) :) 

```
python data-processing.py --input_dir raw-data/QQPPos --output_dir processed-data/QQPPos-hf-refine --use_template Y

python data-processing.py --input_dir raw-data/QQPPos --output_dir processed-data/QQPPos-hf-refine --use_template N
```

**Comment by sunjiao123sun** [comment]
please feel free to reopen the issue if you still have problems, closing
