### ISSUE TITLE
Cannot run the demo code because of StanfordNLPCore

### ISSUE THREAD

**Issue by afonso-sousa** [PlusLabNLP/AESOP#8]
Hi there. I would like to use your work on my research and was trying to run the demo, but was unable to. I think this related to [this issue](https://github.com/PlusLabNLP/AESOP/issues/4#issue-1244289572).I tried with stanford-corenlp-full-2018-10-05 (the one you provide in Google Drive), stanford-corenlp-full-2016-10-31 and stanford-corenlp-4.5.0 and none worked. Either I get `UnboundLocalError: local variable 'new_sent' referenced before assignment` or problems with not finding the parser model in 'edu/stanford/nlp/models/srparser/englishSR.ser.gz'. Do you have any intuition on how can I fix this to run your code? Thanks in advance for any help you can provide.

**Comment by sunjiao123sun** [comment]
Hi there,

Hello from Jiao — it’s right, the error is because  of the inappropriate
set up of Stanford core NLP package. However, I am traveling home tmr, so I
will reply within 2 days with a bit more thoughts.

Talk to you soon.

Best,
Jiao

**Comment by afonso-sousa** [comment]
Sorry to address you again. I am eager to experiment with your research but this issue does not allow me to do so. Do you have any suggestion on how can I solve this issue? Does the package need to be compiled? If so, did you use Maven or Ant? My current problem seems to be with the englishSR.ser.gz parser missing.

**Comment by sunjiao123sun** [comment]
Hi there, it seems that your Stanford CoreNLP parser is missing, and the package does not need to compile. Did you download the required file following the instruction?

> Please download all the required tools, data (our preprocessed data) and software (e.g., stanford CoreNLP) from https://drive.google.com/file/d/1MP9k48BuBCdAPhWXjfuq7Cl9b9ZIdAPB/view?usp=sharing

**Comment by afonso-sousa** [comment]
Thanks for the reply. Just today I tried everything again:

- I created a new conda environment using: `conda create -n aesop python=3.7`
- I deleted the project and cloned it again: `git clone https://github.com/PlusLabNLP/AESOP.git`
- I installed all packages: `pip install -r requirement.txt` (had to fix pytorch to torch, transformers version to non-dev and remove second entry for torch).
- Downloaded `aesop-required.zip` from the link you shared.
- Extracted the contents of the zip to the main directory (/AESOP). At this point, StanfordCoreNLP is at evaluation/apps/stanford-corenlp-full-2018-10-05/
- Ran `python demo.py --output_dir demo_output`
- Missing rouge-score. Installed it: `pip install rouge-score`
- Ran `python demo.py --output_dir demo_output` again.

The output was:

> CompletedProcess(args=['java', '-cp', '../evaluation/apps/stanford-corenlp-full-2018-10-05/*', '-Xmx40g', 'edu.stanford.nlp.pipeline.StanfordCoreNLP', '-parse.model', 'edu/stanford/nlp/models/srparser/englishSR.ser.gz', '-annotators', 'tokenize,ssplit,pos,parse', '-ssplit.eolonly', '-outputFormat', 'text', '-outputDirectory', '/tmp/tmpzsos3uu8', '-file', 'demo-input-data.txt'], returncode=1, stdout=b'', stderr=b'Error: Could not find or load main class edu.stanford.nlp.pipeline.StanfordCoreNLP\n')
> Traceback (most recent call last):
>   File "demo.py", line 11, in <module>
>     src_pure_parses, src_parses = spe.run(file_path)
>   File "/home/admin/projects/AESOP/helper/utils.py", line 157, in run
>     extract_parses(parsed_file)], [e['parse'] for e in extract_parses(parsed_file)]
>   File "/home/admin/projects/AESOP/helper/utils.py", line 59, in extract_parses
>     f = codecs.getreader('utf-8')(open(fname, 'rb'))
> FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpzsos3uu8/demo-input-data.txt.out'

- Changed `STANFORD_CORENLP = '../evaluation/apps/stanford-corenlp-full-2018-10-05'`to `STANFORD_CORENLP = './evaluation/apps/stanford-corenlp-full-2018-10-05'`.
- Ran `python demo.py --output_dir demo_output` again.

> standford corenlp path: ./evaluation/apps/stanford-corenlp-full-2018-10-05/*
> parsing file: demo-input-data.txt
> CompletedProcess(args=['java', '-cp', './evaluation/apps/stanford-corenlp-full-2018-10-05/*', '-Xmx40g', 'edu.stanford.nlp.pipeline.StanfordCoreNLP', '-parse.model', 'edu/stanford/nlp/models/srparser/englishSR.ser.gz', '-annotators', 'tokenize,ssplit,pos,parse', '-ssplit.eolonly', '-outputFormat', 'text', '-outputDirectory', '/tmp/tmpembmu73c', '-file', 'demo-input-data.txt'], returncode=0, stdout=b'', stderr=b'[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator tokenize\n[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ssplit\n[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator pos\n[main] INFO edu.stanford.nlp.tagger.maxent.MaxentTagger - Loading POS tagger from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [0.6 sec].\n[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator parse\n[main] INFO edu.stanford.nlp.parser.common.ParserGrammar - Loading parser from serialized file edu/stanford/nlp/models/srparser/englishSR.ser.gz ... done [7.6 sec].\n\nProcessing file /home/admin/projects/AESOP/demo-input-data.txt ... writing to /tmp/tmpembmu73c/demo-input-data.txt.out\nAnnotating file /home/admin/projects/AESOP/demo-input-data.txt ... done [0.4 sec].\n\nAnnotation pipeline timing information:\nTokenizerAnnotator: 0.0 sec.\nWordsToSentencesAnnotator: 0.0 sec.\nPOSTaggerAnnotator: 0.1 sec.\nParserAnnotator: 0.3 sec.\nTOTAL: 0.4 sec. for 89 tokens at 204.6 tokens/sec.\nPipeline setup: 8.2 sec.\nTotal time for StanfordCoreNLP pipeline: 8.7 sec.\n')
> Traceback (most recent call last):
>   File "demo.py", line 11, in <module>
>     src_pure_parses, src_parses = spe.run(file_path)
>   File "/home/admin/projects/AESOP/helper/utils.py", line 157, in run
>     extract_parses(parsed_file)], [e['parse'] for e in extract_parses(parsed_file)]
>   File "/home/admin/projects/AESOP/helper/utils.py", line 82, in extract_parses
>     elif new_sent:
> UnboundLocalError: local variable 'new_sent' referenced before assignment

- As you said in [this issue](https://github.com/PlusLabNLP/AESOP/issues/4#issue-1244289572), I downloaded `stanford-corenlp-full-2016-10-31` from https://stanfordnlp.github.io/CoreNLP/history.html and replaced `stanford-corenlp-full-2018-10-05`.
- Ran `python demo.py --output_dir demo_output` again.

> standford corenlp path: ./evaluation/apps/stanford-corenlp-full-2016-10-31/*
> parsing file: demo-input-data.txt
> CompletedProcess(args=['java', '-cp', './evaluation/apps/stanford-corenlp-full-2016-10-31/*', '-Xmx40g', 'edu.stanford.nlp.pipeline.StanfordCoreNLP', '-parse.model', 'edu/stanford/nlp/models/srparser/englishSR.ser.gz', '-annotators', 'tokenize,ssplit,pos,parse', '-ssplit.eolonly', '-outputFormat', 'text', '-outputDirectory', '/tmp/tmpxwzhh5nj', '-file', 'demo-input-data.txt'], returncode=1, stdout=b'', stderr=b'[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator tokenize\n[main] INFO edu.stanford.nlp.pipeline.TokenizerAnnotator - No tokenizer type provided. Defaulting to PTBTokenizer.\n[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ssplit\n[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator pos\n[main] INFO edu.stanford.nlp.tagger.maxent.MaxentTagger - Loading POS tagger from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [0.6 sec].\n[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator parse\nException in thread "main" edu.stanford.nlp.io.RuntimeIOException: java.io.IOException: Unable to open "edu/stanford/nlp/models/srparser/englishSR.ser.gz" as class path, filename or URL\n\tat edu.stanford.nlp.parser.common.ParserGrammar.loadModel(ParserGrammar.java:187)\n\tat edu.stanford.nlp.pipeline.ParserAnnotator.loadModel(ParserAnnotator.java:219)\n\tat edu.stanford.nlp.pipeline.ParserAnnotator.<init>(ParserAnnotator.java:121)\n\tat edu.stanford.nlp.pipeline.AnnotatorImplementations.parse(AnnotatorImplementations.java:163)\n\tat edu.stanford.nlp.pipeline.AnnotatorFactories$11.create(AnnotatorFactories.java:359)\n\tat edu.stanford.nlp.pipeline.AnnotatorPool.get(AnnotatorPool.java:152)\n\tat edu.stanford.nlp.pipeline.StanfordCoreNLP.construct(StanfordCoreNLP.java:451)\n\tat edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:154)\n\tat edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:150)\n\tat edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:137)\n\tat edu.stanford.nlp.pipeline.StanfordCoreNLP.main(StanfordCoreNLP.java:1323)\nCaused by: java.io.IOException: Unable to open "edu/stanford/nlp/models/srparser/englishSR.ser.gz" as class path, filename or URL\n\tat edu.stanford.nlp.io.IOUtils.getInputStreamFromURLOrClasspathOrFileSystem(IOUtils.java:470)\n\tat edu.stanford.nlp.io.IOUtils.readObjectFromURLOrClasspathOrFileSystem(IOUtils.java:309)\n\tat edu.stanford.nlp.parser.common.ParserGrammar.loadModel(ParserGrammar.java:184)\n\t... 10 more\n')
> Traceback (most recent call last):
>   File "demo.py", line 11, in <module>
>     src_pure_parses, src_parses = spe.run(file_path)
>   File "/home/admin/projects/AESOP/helper/utils.py", line 158, in run
>     extract_parses(parsed_file)], [e['parse'] for e in extract_parses(parsed_file)]
>   File "/home/admin/projects/AESOP/helper/utils.py", line 59, in extract_parses
>     f = codecs.getreader('utf-8')(open(fname, 'rb'))
> FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpxwzhh5nj/demo-input-data.txt.out'

Notice in the stack trace where it says `Unable to open "edu/stanford/nlp/models/srparser/englishSR.ser.gz`. I cannot disentangle from here. Do you have any suggestions?

**Comment by sunjiao123sun** [comment]
What will happen if you directly run that java command?

**Comment by afonso-sousa** [comment]
The following command actually works in the terminal: `java -cp "./evaluation/apps/stanford-corenlp-full-2018-10-05/*" -Xmx40g edu.stanford.nlp.pipeline.StanfordCoreNLP -parse.model edu/stanford/nlp/models/srparser/englishSR.ser.gz -annotators tokenize,ssplit,pos,parse -ssplit.eolonly -outputFormat text -file demo-input-data.txt` for `stanford-corenlp-full-2018-10-05`. Does this suggest that the `UnboundLocalError: local variable 'new_sent' referenced before assignment` may be a coding problem?

**Comment by afonso-sousa** [comment]
I tried switching line 76 for `if data != {'tokens':[], 'pos':[], 'parse':'', 'deps':[]}: sentences.append(data)` as suggested in [this issue](https://github.com/PlusLabNLP/AESOP/issues/4#issue-1244289572), but the problem remains.

**Comment by afonso-sousa** [comment]
The generated file from the command starts with:

> Document: ID=demo-input-data.txt (7 sentences, 89 tokens)
> 
> Sentence #1 (10 tokens):
> Your drawing is so bright even sunshine adjusts focus!

So, in the first line, the code will always end up going for the `elif new_sent` which is not declared yet. What was the purpose of this `new_sent` variable? As I understand it, it was to know when to set the `new_pos`, but this seems irrelevant since every POS line seems to start with the `[Text=`. Do you have any ideas on how can this be quickly fixed?

**Comment by sunjiao123sun** [comment]
No, it's not a coding problem, otherwise, we won't have many people already executed the program, and I would strongly suggest against changing the script.

when I revisit your code: 

> Changed STANFORD_CORENLP = '../evaluation/apps/stanford-corenlp-full-2018-10-05'to STANFORD_CORENLP = './evaluation/apps/stanford-corenlp-full-2018-10-05'.

can you make sure you setup the right path for the corenlp package? the "../" means upper directory, "./" means current directory.

also,

> Document: ID=demo-input-data.txt (7 sentences, 89 tokens)

Sentence https://github.com/PlusLabNLP/AESOP/issues/1 (10 tokens):
Your drawing is so bright even sunshine adjusts focus!

Is the constituency parsing in here?

**Comment by afonso-sousa** [comment]
If it is not a coding problem, the parser outputs should be different because I get the `new_sent is not declared`. If I instantiate all variables (new_sent, new_pos, new_parse, new_deps) as False before the loop it does run but when up if problems in another line. I believe the output I am getting from the parser is a bit different from the intended output (do not know why because I am using the stanford-corenlp-full-2018-10-05 you provided).
As I am running `python demo.py --output_dir demo_output` from the root directory (AESOP), the `evaluation` folder is a child folder, so I had to use "./" instead of "../".
The parser output seems to have everything. It goes something like:

> Document: ID=demo-input-data.txt (7 sentences, 89 tokens)
> 
> Sentence #1 (10 tokens):
> Your drawing is so bright even sunshine adjusts focus!
> 
> Tokens:
> [Text=Your CharacterOffsetBegin=0 CharacterOffsetEnd=4 PartOfSpeech=PRP$]
> [Text=drawing CharacterOffsetBegin=5 CharacterOffsetEnd=12 PartOfSpeech=NN]
> ...
> [Text=focus CharacterOffsetBegin=48 CharacterOffsetEnd=53 PartOfSpeech=NN]
> [Text=! CharacterOffsetBegin=53 CharacterOffsetEnd=54 PartOfSpeech=.]
> 
> Constituency parse: 
> (ROOT
>   (S
>     (NP (PRP$ Your) (NN drawing))
> ...
>     (VP (VBZ adjusts)
>       (NP (NN focus)))
>     (. !)))
> 
> 
> Dependency Parse (enhanced plus plus dependencies):
> root(ROOT-0, adjusts-8)
> ...
> punct(adjusts-8, !-10)
> 
> Sentence #2 (16 tokens):
> Singapore's management is so reliable even Singapore will improve the health of a person!
> 
> Tokens:
> [Text=Singapore CharacterOffsetBegin=55 CharacterOffsetEnd=64 PartOfSpeech=NNP]
> [Text='s CharacterOffsetBegin=64 CharacterOffsetEnd=66 PartOfSpeech=POS]
> ...
> [Text=person CharacterOffsetBegin=137 CharacterOffsetEnd=143 PartOfSpeech=NN]
> [Text=! CharacterOffsetBegin=143 CharacterOffsetEnd=144 PartOfSpeech=.]
> 
> Constituency parse: 
> (ROOT
>   (S
>     (NP
>       (NP (NNP Singapore) (POS 's))
> ...
>                 (PP (IN of)
>                   (NP (DT a) (NN person)))))))))
>     (. !)))
> 
> 
> Dependency Parse (enhanced plus plus dependencies):
> root(ROOT-0, is-4)
> ...
> nmod:of(health-12, person-15)
> punct(is-4, !-16)
> 
> Sentence #3 (16 tokens):
> Young artists are so productive even their subject matter focuses your attention on that subject!
>

**Comment by sunjiao123sun** [comment]
set a breakpoint here: https://github.com/PlusLabNLP/AESOP/blob/master/helper/utils.py#L146. what does it say?

**Comment by afonso-sousa** [comment]
`out` prints:

> CompletedProcess(args=['java', '-cp', './evaluation/apps/stanford-corenlp-full-2018-10-05/*', '-Xmx40g', 'edu.stanford.nlp.pipeline.StanfordCoreNLP', '-parse.model', 'edu/stanford/nlp/models/srparser/englishSR.ser.gz', '-annotators', 'tokenize,ssplit,pos,parse', '-ssplit.eolonly', '-outputFormat', 'text', '-outputDirectory', '/tmp/tmps_e5vsur', '-file', 'demo-input-data.txt'], returncode=0, stdout=b'', stderr=b'[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator tokenize\n[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ssplit\n[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator pos\n[main] INFO edu.stanford.nlp.tagger.maxent.MaxentTagger - Loading POS tagger from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [0.5 sec].\n[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator parse\n[main] INFO edu.stanford.nlp.parser.common.ParserGrammar - Loading parser from serialized file edu/stanford/nlp/models/srparser/englishSR.ser.gz ... done [7.3 sec].\n\nProcessing file /home/admin/projects/AESOP/demo-input-data.txt ... writing to /tmp/tmps_e5vsur/demo-input-data.txt.out\nAnnotating file /home/admin/projects/AESOP/demo-input-data.txt ... done [0.6 sec].\n\nAnnotation pipeline timing information:\nTokenizerAnnotator: 0.0 sec.\nWordsToSentencesAnnotator: 0.0 sec.\nPOSTaggerAnnotator: 0.0 sec.\nParserAnnotator: 0.5 sec.\nTOTAL: 0.6 sec. for 89 tokens at 153.4 tokens/sec.\nPipeline setup: 7.9 sec.\nTotal time for StanfordCoreNLP pipeline: 8.5 sec.\n')

**Comment by sunjiao123sun** [comment]
Let's do zoom.

Join Zoom Meeting
https://usc.zoom.us/j/8373245899

**Comment by afonso-sousa** [comment]
I finally did it. Along with the remarks in [this issue](https://github.com/PlusLabNLP/AESOP/issues/4), the `sentence_splitter` can be found [here](https://github.com/huggingface/transformers/blob/main/examples/research_projects/seq2seq-distillation/sentence_splitter.py) and the PyTorch version that worked for me was 1.7.1 (neither 1.8.0 nor 1.3.0 did the job). The Stanford version has to be 3.7.0 ( go to https://stanfordnlp.github.io/CoreNLP/history.html and download both the stanford-corenlp-full-216-10-31 as well as the English and English kbp and place them in the stanford directory). This setting worked for me to run all steps of the demo.
